map_place_add:
    path:     /place/{name}/{lat}/{lng}
    defaults: { _controller: TgpMapBundle:Place:add }
    requirements:
        _method:    POST
        
map_place_remove:
    path:     /place/{name}/{lat}/{lng}
    defaults: { _controller: TgpMapBundle:Place:remove }
    requirements:
        _method:    DELETE

map_place_list:
    path:     /place/
    defaults: { _controller: TgpMapBundle:Place:list }
    requirements:
        _method:    GET

map_place_search:
    path:     /place/search/{request}
    defaults: { _controller: TgpMapBundle:Place:search }
    requirements:
        _method:    GET

#get_friends_places:
#    path:     /getfriendsplacelist
#    defaults: { _controller: TgpMapBundle:GetFriendsPlaceList:get }
#    requirements:
#        _method:    GET

get_friend_places:
    path:     /place/friend/{id}/{name}
    defaults: { _controller: TgpMapBundle:GetFriendPlaceList:get }
    requirements:
        _method:    GET

