user_friend_list:
    path:     /friend/
    defaults: { _controller: TgpUserBundle:Friend:list }
    requirements:
        _method:    GET

user_friend_get:
    path:     /friend/search/{nameoremail}
    defaults: { _controller: TgpUserBundle:Friend:get }
    requirements:
        _method:    GET

user_friend_add:
    path:     /friend/{name}
    defaults: { _controller: TgpUserBundle:Friend:add }
    requirements:
        _method:    POST

user_friend_remove:
    path:     /friend/{name}
    defaults: { _controller: TgpUserBundle:Friend:remove }
    requirements:
        _method:    DELETE

